### ISSUE TITLE
Is this an active project?

### ISSUE THREAD

**Issue by iprdp** [yiiext/yii2-yii-bridge#14]
Hello Guys,

Since I unable to find any other channels to talk to you I am creating this issue.

Is this an active project? I am starting to work on migration project from yii1 to yii2 and have been working on these same lines. I would like to know and contribute if this is an active project.

Thanks for any info!

**Comment by cebe** [comment]
the project is being watched by a few people. If you are willing to help to keep it active, you are very welcome to do so.

**Comment by slavcodev** [comment]
Closing the issue, the library is no longer maintained.
