### ISSUE TITLE
What is the use of ActiveQuery ?

### ISSUE THREAD

**Issue by ahmadasjad** [yiiext/yii2-yii-bridge#16]

**Comment by samdark** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#querying-data

**Comment by ahmadasjad** [comment]
I actually Asked about the file available in this extension:[https://github.com/yiiext/yii2-yii-bridge/blob/master/src/Db/ActiveQuery.php]( https://github.com/yiiext/yii2-yii-bridge/blob/master/src/Db/ActiveQuery.php).

I actually didn't see a single use of this file

**Comment by samdark** [comment]
@slavcodev do you remember how it was used?

**Comment by slavcodev** [comment]
Something like 
```
// Using `ActiveQuery` from Yii2 with CActiveRecord (Yii1)
class Comment extends \CActiveRecord
{
    public static function query()
    {
        return new \Slavcodev\YiiBridge\Db(get_called_class());
    }
}
```
then
```
$customer = Customer::query()->all
```

**Comment by slavcodev** [comment]
I'm not sure it's working now though. Since this library was drafted when Yii2 was on very early versions, even maybe beta. I don't recall.

@samdark Can you mark this repository as abandoned/archived?

**Comment by ahmadasjad** [comment]
Thanks @slavcodev, for the quick answer. 

This solution is no longer going to work as there are lots of code improvement in Yii2 from the time you made this extension. 
After all, your comment and the extension has gaven me ideas to handle the situation.

I also recommend marking it abandoned
